#pragma once

/*
 * Copyright (C) 2020 Torsten Brischalle
 *
 * AutomatisierungsTechnik Voigt GmbH
 * Heilbronner Str. 17
 * 01189 Dresden
 * Germany
 *
 * web:   https://www.atv-systems.de
 * email: atv@atv-systems.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

namespace k4200
{
    /// <summary>
    /// K4200 lpt library instrument IDs.
    /// </summary>
    enum K4200Instruments
    {
        KI_EOC = 0,
        KI_NOINSTR = 0,
        MINNAME = 4096,
        GND = MINNAME,
        GNDU = GND,
        GNDUF = GNDU,
        SMU1L = GNDU,
        SMU1OL = SMU1L,
        SMU2L = GNDU,
        SMU2OL = SMU2L,
        SMU3L = GNDU,
        SMU3OL = SMU3L,
        SMU4L = GNDU,
        SMU4OL = SMU4L,
        SMU5L = GNDU,
        SMU5OL = SMU5L,
        SMU6L = GNDU,
        SMU6OL = SMU6L,
        SMU7L = GNDU,
        SMU7OL = SMU7L,
        SMU8L = GNDU,
        SMU8OL = SMU8L,
        SMU9L = GNDU,
        SMU9OL = SMU9L,
        SMU10L = GNDU,
        SMU10OL = SMU10L,
        GPT1L = GNDU,
        GPT1OL = GPT1L,
        GPT2L = GNDU,
        GPT2OL = GPT2L,
        GPT3L = GNDU,
        GPT3OL = GPT3L,
        GPT4L = GNDU,
        GPT4OL = GPT4L,
        GPT5L = GNDU,
        GPT5OL = GPT5L,
        GPT6L = GNDU,
        GPT6OL = GPT6L,
        GPT7L = GNDU,
        GPT7OL = GPT7L,
        GPT8L = GNDU,
        GPT8OL = GPT8L,
        GNDUS,
        CHUCK,
        KI_SYSTEM,
        SMU1,
        SMU1F = SMU1,
        SMU1H = SMU1,
        SMU1OH = SMU1,
        SMU1S,
        SMU1SH = SMU1S,
        SMU2,
        SMU2F = SMU2,
        SMU2H = SMU2,
        SMU2OH = SMU2,
        SMU2S,
        SMU2SH = SMU2S,
        SMU3,
        SMU3F = SMU3,
        SMU3H = SMU3,
        SMU3OH = SMU3,
        SMU3S,
        SMU3SH = SMU3S,
        SMU4,
        SMU4F = SMU4,
        SMU4H = SMU4,
        SMU4OH = SMU4,
        SMU4S,
        SMU4SH = SMU4S,
        SMU5,
        SMU5F = SMU5,
        SMU5H = SMU5,
        SMU5OH = SMU5,
        SMU5S,
        SMU5SH = SMU5S,
        SMU6,
        SMU6F = SMU6,
        SMU6H = SMU6,
        SMU6OH = SMU6,
        SMU6S,
        SMU6SH = SMU6S,
        SMU7,
        SMU7F = SMU7,
        SMU7H = SMU7,
        SMU7OH = SMU7,
        SMU7S,
        SMU7SH = SMU7S,
        SMU8,
        SMU8F = SMU8,
        SMU8H = SMU8,
        SMU8OH = SMU8,
        SMU8S,
        SMU8SH = SMU8S,
        SMU9,
        SMU9F = SMU9,
        SMU9H = SMU9,
        SMU9OH = SMU9,
        SMU9S,
        SMU9SH = SMU9S,
        SMU10,
        SMU10F = SMU10,
        SMU10H = SMU10,
        SMU10OH = SMU10,
        SMU10S,
        SMU10SH = SMU10S,
        GPT1,
        GPT1F = GPT1,
        GPT1H = GPT1,
        GPT1OH = GPT1,
        GPT1S,
        GPT1SH = GPT1S,
        GPT2,
        GPT2F = GPT2,
        GPT2H = GPT2,
        GPT2OH = GPT2,
        GPT2S,
        GPT2SH = GPT2S,
        GPT3,
        GPT3F = GPT3,
        GPT3H = GPT3,
        GPT3OH = GPT3,
        GPT3S,
        GPT3SH = GPT3S,
        GPT4,
        GPT4F = GPT4,
        GPT4H = GPT4,
        GPT4OH = GPT4,
        GPT4S,
        GPT4SH = GPT4S,
        GPT5,
        GPT5F = GPT5,
        GPT5H = GPT5,
        GPT5OH = GPT5,
        GPT5S,
        GPT5SH = GPT5S,
        GPT6,
        GPT6F = GPT6,
        GPT6H = GPT6,
        GPT6OH = GPT6,
        GPT6S,
        GPT6SH = GPT6S,
        GPT7,
        GPT7F = GPT7,
        GPT7H = GPT7,
        GPT7OH = GPT7,
        GPT7S,
        GPT7SH = GPT7S,
        GPT8,
        GPT8F = GPT8,
        GPT8H = GPT8,
        GPT8OH = GPT8,
        GPT8S,
        GPT8SH = GPT8S,
        CMTR1,
        CMTR1H = CMTR1,
        CMTR1L,
        CMTR1V,
        CMTR1R,
        CMTR2,
        CMTR2H = CMTR2,
        CMTR2L,
        CMTR2V,
        CMTR2R,
        CMTR3,
        CMTR3H = CMTR3,
        CMTR3L,
        CMTR3V,
        CMTR3R,
        CMTR4,
        CMTR4H = CMTR4,
        CMTR4L,
        CMTR4V,
        CMTR4R,
        IMTR1,
        IMTR1H = IMTR1,
        IMTR1L,
        IMTR2,
        IMTR2H = IMTR2,
        IMTR2L,
        IMTR3,
        IMTR3H = IMTR3,
        IMTR3L,
        IMTR4,
        IMTR4H = IMTR4,
        IMTR4L,
        VMTR1,
        VMTR1H = VMTR1,
        VMTR1L,
        VMTR2,
        VMTR2H = VMTR2,
        VMTR2L,
        VMTR3,
        VMTR3H = VMTR3,
        VMTR3L,
        VMTR4,
        VMTR4H = VMTR4,
        VMTR4L,
        VSRC1,
        VSRC1H = VSRC1,
        VSRC1L,
        VSRC2,
        VSRC2H = VSRC2,
        VSRC2L,
        VSRC3,
        VSRC3H = VSRC3,
        VSRC3L,
        VSRC4,
        VSRC4H = VSRC4,
        VSRC4L,
        VSRC5,
        VSRC5H = VSRC5,
        VSRC5L,
        VSRC6,
        VSRC6H = VSRC6,
        VSRC6L,
        VSRC7,
        VSRC7H = VSRC7,
        VSRC7L,
        VSRC8,
        VSRC8H = VSRC8,
        VSRC8L,
        ISRC1,
        ISRC1H = ISRC1,
        ISRC1L,
        ISRC2,
        ISRC2H = ISRC2,
        ISRC2L,
        ISRC3,
        ISRC3H = ISRC3,
        ISRC3L,
        ISRC4,
        ISRC4H = ISRC4,
        ISRC4L,
        SIO1,
        SIO2,
        SIO3,
        SIO4,
        SIO5,
        SIO6,
        PIO1,
        PIO2,
        PIO3,
        PIO4,
        PIO5,
        PIO6,
        PIO7,
        PIO8,
        PIO9,
        PIO10,
        TIMER1,
        TIMER2,
        TIMER3,
        TIMER4,
        PRBR1,
        PROBER1 = PRBR1,
        PRBR2,
        PROBER2 = PRBR2,
        PRBR3,
        PROBER3 = PRBR3,
        PRBR4,
        PROBER4 = PRBR4,
        FAKE,
        FAKE1 = FAKE,
        FAKE2,
        FAKE3,
        FAKE4,
        MTRX1,
        MATRIX1 = MTRX1,
        MTRX2,
        MATRIX2 = MTRX2,
        MTRX3,
        MATRIX3 = MTRX3,
        MTRX4,
        MATRIX4 = MTRX4,
        GPI1,
        GPI1H = GPI1,
        GPI1L,
        GPI1SH,
        GPI1SL,
        GPI2,
        GPI2H = GPI2,
        GPI2L,
        GPI2SH,
        GPI2SL,
        GPI3,
        GPI3H = GPI3,
        GPI3L,
        GPI3SH,
        GPI3SL,
        GPI4,
        GPI4H = GPI4,
        GPI4L,
        GPI4SH,
        GPI4SL,
        GPI5,
        GPI5H = GPI5,
        GPI5L,
        GPI5SH,
        GPI5SL,
        GPI6,
        GPI6H = GPI6,
        GPI6L,
        GPI6SH,
        GPI6SL,
        GPI7,
        GPI7H = GPI7,
        GPI7L,
        GPI7SH,
        GPI7SL,
        GPI8,
        GPI8H = GPI8,
        GPI8L,
        GPI8SH,
        GPI8SL,
        PGU1,
        PGU2,
        PGU3,
        PGU4,
        PGU5,
        PGU6,
        PGU7,
        PGU8,
        PGU9,
        PGU10,
        PGU11,
        PGU12,
        PGU13,
        PGU14,
        PGU15,
        PGU16,
        VPU1,
        VPU1CH1 = VPU1,
        VPU1CH2,
        VPU2,
        VPU2CH1 = VPU2,
        VPU2CH2,
        VPU3,
        VPU3CH1 = VPU3,
        VPU3CH2,
        VPU4,
        VPU4CH1 = VPU4,
        VPU4CH2,
        VPU5,
        VPU5CH1 = VPU5,
        VPU5CH2,
        VPU6,
        VPU6CH1 = VPU6,
        VPU6CH2,
        VPU7,
        VPU7CH1 = VPU7,
        VPU7CH2,
        VPU8,
        VPU8CH1 = VPU8,
        VPU8CH2,
        VPU9,
        VPU9CH1 = VPU9,
        VPU9CH2,
        VPU10,
        VPU10CH1 = VPU10,
        VPU10CH2,
        VPU11,
        VPU11CH1 = VPU11,
        VPU11CH2,
        VPU12,
        VPU12CH1 = VPU12,
        VPU12CH2,
        VPU13,
        VPU13CH1 = VPU13,
        VPU13CH2,
        VPU14,
        VPU14CH1 = VPU14,
        VPU14CH2,
        VPU15,
        VPU15CH1 = VPU15,
        VPU15CH2,
        VPU16,
        VPU16CH1 = VPU16,
        VPU16CH2,
        PMU1,
        PMU1CH1 = PMU1,
        PMU1CH2,
        PMU2,
        PMU2CH1 = PMU2,
        PMU2CH2,
        PMU3,
        PMU3CH1 = PMU3,
        PMU3CH2,
        PMU4,
        PMU4CH1 = PMU4,
        PMU4CH2,
        PMU5,
        PMU5CH1 = PMU5,
        PMU5CH2,
        PMU6,
        PMU6CH1 = PMU6,
        PMU6CH2,
        PMU7,
        PMU7CH1 = PMU7,
        PMU7CH2,
        PMU8,
        PMU8CH1 = PMU8,
        PMU8CH2,
        PMU9,
        PMU9CH1 = PMU9,
        PMU9CH2,
        PMU10,
        PMU10CH1 = PMU10,
        PMU10CH2,
        PMU11,
        PMU11CH1 = PMU11,
        PMU11CH2,
        PMU12,
        PMU12CH1 = PMU12,
        PMU12CH2,
        PMU13,
        PMU13CH1 = PMU13,
        PMU13CH2,
        PMU14,
        PMU14CH1 = PMU14,
        PMU14CH2,
        PMU15,
        PMU15CH1 = PMU15,
        PMU15CH2,
        PMU16,
        PMU16CH1 = PMU16,
        PMU16CH2,
        OSC1,
        OSC1INP1 = OSC1,
        OSC1INP2,
        OSC2,
        OSC2INP1 = OSC2,
        OSC2INP2,
        OSC3,
        OSC3INP1 = OSC3,
        OSC3INP2,
        OSC4,
        OSC4INP1 = OSC4,
        OSC4INP2,
        OSC5,
        OSC5INP1 = OSC5,
        OSC5INP2,
        OSC6,
        OSC6INP1 = OSC6,
        OSC6INP2,
        OSC7,
        OSC7INP1 = OSC7,
        OSC7INP2,
        OSC8,
        OSC8INP1 = OSC8,
        OSC8INP2,
        GPIB1,
        GPIB2,
        GPIB3,
        GPIB4,
        TF1,
        FOHM1,
        FOHM2,
        FOHM3,
        FOHM4,
        FOHM5,
        FOHM6,
        FOHM7,
        FOHM8,
        FOHMTERM,
        KI_UNKINS,
        BEEPER1,
        BEEPER2,
        BEEPER3,
        BEEPER4,
        ES1,
        ES2,
        ES3,
        ES4,
        CVU1,
        CVU1HPOT = CVU1,
        CVU1HCUR,
        CVU1LCUR,
        CVU1LPOT,
        CVU2,
        CVU2HPOT = CVU2,
        CVU2HCUR,
        CVU2LCUR,
        CVU2LPOT,
        CVU3,
        CVU3HPOT = CVU3,
        CVU3HCUR,
        CVU3LCUR,
        CVU3LPOT,
        CVU4,
        CVU4HPOT = CVU4,
        CVU4HCUR,
        CVU4LCUR,
        CVU4LPOT,
        CVU5,
        CVU5HPOT = CVU5,
        CVU5HCUR,
        CVU5LCUR,
        CVU5LPOT,
        CVU6,
        CVU6HPOT = CVU6,
        CVU6HCUR,
        CVU6LCUR,
        CVU6LPOT,
        CVU7,
        CVU7HPOT = CVU7,
        CVU7HCUR,
        CVU7LCUR,
        CVU7LPOT,
        CVU8,
        CVU8HPOT = CVU8,
        CVU8HCUR,
        CVU8LCUR,
        CVU8LPOT,
        CVU9,
        CVU9HPOT = CVU9,
        CVU9HCUR,
        CVU9LCUR,
        CVU9LPOT,
        CVU10,
        CVU10HPOT = CVU10,
        CVU10HCUR,
        CVU10LCUR,
        CVU10LPOT,
        CVIV1,
        CVIV2,
        REF1,
        REF2,
        REF3,
        VIMS1,
        VIMS1H,
        VIMS1L,
        VIMS2,
        VIMS2H,
        VIMS2L,
        VIMS3,
        VIMS3H,
        VIMS3L,
        VIMS4,
        VIMS4H,
        VIMS4L,
        VIMS5,
        VIMS5H,
        VIMS5L,
        VIMS6,
        VIMS6H,
        VIMS6L,
        VIMS7,
        VIMS7H,
        VIMS7L,
        VIMS8,
        VIMS8H,
        VIMS8L,
        VIMS9,
        VIMS9H,
        VIMS9L,
        VIMS10,
        VIMS10H,
        VIMS10L,
        VIMS11,
        VIMS11H,
        VIMS11L,
        VIMS12,
        VIMS12H,
        VIMS12L,
        VIMS13,
        VIMS13H,
        VIMS13L,
        VIMS14,
        VIMS14H,
        VIMS14L,
        VIMS15,
        VIMS15H,
        VIMS15L,
        VIMS16,
        VIMS16H,
        VIMS16L,
        FMTR1,
        FMTR2,
        FMTR3,
        FMTR4,
        SYMTR,
        SYMTRH,
        SYMTRL,
        LCRM,
        PSRC1,
        PSRC1H = PSRC1,
        PSRC1L,
        PSRC2,
        PSRC2H = PSRC2,
        PSRC2L,
        PSRC3,
        PSRC3H = PSRC3,
        PSRC3L,
        PSRC4,
        PSRC4H = PSRC4,
        PSRC4L,
        RSRC1,
        RSRC1H = RSRC1,
        RSRC1L,
        RSRC2,
        RSRC2H = RSRC2,
        RSRC2L,
        RSRC3,
        RSRC3H = RSRC3,
        RSRC3L,
        RSRC4,
        RSRC4H = RSRC4,
        RSRC4L,
        QSRC1,
        QSRC1H = QSRC1,
        QSRC1L,
        QSRC2,
        QSRC2H = QSRC2,
        QSRC2L,
        QSRC3,
        QSRC3H = QSRC3,
        QSRC3L,
        QSRC4,
        QSRC4H = QSRC4,
        QSRC4L,
        IMON1,
        IMON1H = IMON1,
        IMON1L,
        IMON2,
        IMON2H = IMON2,
        IMON2L,
        IMON3,
        IMON3H = IMON3,
        IMON3L,
        IMON4,
        IMON4H = IMON4,
        IMON4L,
        VMON1,
        VMON1H = VMON1,
        VMON1L,
        VMON2,
        VMON2H = VMON2,
        VMON2L,
        VMON3,
        VMON3H = VMON3,
        VMON3L,
        VMON4,
        VMON4H = VMON4,
        VMON4L,
        VMON5,
        VMON5H = VMON5,
        VMON5L,
        VMON6,
        VMON6H = VMON6,
        VMON6L,
        VMON7,
        VMON7H = VMON7,
        VMON7L,
        VMON8,
        VMON8H = VMON8,
        VMON8L,
        QMTR1,
        QMTR1H = QMTR1,
        QMTR1L,
        QMTR2,
        QMTR2H = QMTR2,
        QMTR2L,
        QMTR3,
        QMTR3H = QMTR3,
        QMTR3L,
        QMTR4,
        QMTR4H = QMTR4,
        QMTR4L,
        RMTR1,
        RMTR1H = RMTR1,
        RMTR1L,
        RMTR1SH,
        RMTR1SL,
        RMTR2,
        RMTR2H = RMTR2,
        RMTR2L,
        RMTR2SH,
        RMTR2SL,
        RMTR3,
        RMTR3H = RMTR3,
        RMTR3L,
        RMTR3SH,
        RMTR3SL,
        RMTR4,
        RMTR4H = RMTR4,
        RMTR4L,
        RMTR4SH,
        RMTR4SL,
        AUXM,
        ACCU1,
        ACCU1H,
        ACCU1L,
        JUMPER,
        SRU1,
        SRU2,
        SRU3,
        SRU4,
        SRU5,
        SRU6,
        SRU7,
        SRU8,
        UNUSED_PINS = 5000
    };

} // namespace k4200

